-- ============================================================================
-- MIGRATION: Fix Ledger Posting Authorization (System vs Accountant)
-- ============================================================================
-- FIXES authorization so system-generated postings (Retail) are allowed
-- without posted_by_accountant_id, while manual accountant postings remain
-- restricted.
--
-- Problem: Current guard requires posted_by_accountant_id for ALL postings,
-- blocking automatic retail postings which are system-generated.
--
-- Solution:
-- 1. Add posting_source column to distinguish system vs accountant postings
-- 2. Update authorization guard to only require posted_by_accountant_id for
--    accountant postings
-- 3. Update post_journal_entry() to accept posting_source parameter
-- 4. Update post_sale_to_ledger() to use posting_source = 'system'
-- ============================================================================

-- ============================================================================
-- STEP 1: Add posting_source column to journal_entries
-- ============================================================================
-- Add column with DEFAULT to let PostgreSQL automatically backfill existing rows
-- This avoids the immutability trigger issue since PostgreSQL backfills atomically
ALTER TABLE journal_entries
  ADD COLUMN IF NOT EXISTS posting_source TEXT 
    CHECK (posting_source IN ('system', 'accountant'))
    DEFAULT 'accountant';

-- If column already existed (from a previous failed migration), we need to handle NULLs
-- Temporarily disable the immutability trigger to allow UPDATE
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM journal_entries WHERE posting_source IS NULL
  ) THEN
    -- Temporarily disable trigger to allow UPDATE
    ALTER TABLE journal_entries DISABLE TRIGGER trigger_prevent_journal_entry_modification;
    
    UPDATE journal_entries
    SET posting_source = 'accountant'
    WHERE posting_source IS NULL;
    
    -- Re-enable trigger
    ALTER TABLE journal_entries ENABLE TRIGGER trigger_prevent_journal_entry_modification;
  END IF;
END $$;

-- Make posting_source NOT NULL after setting defaults
ALTER TABLE journal_entries
  ALTER COLUMN posting_source SET NOT NULL,
  ALTER COLUMN posting_source SET DEFAULT 'accountant';

-- Index for posting_source
CREATE INDEX IF NOT EXISTS idx_journal_entries_posting_source ON journal_entries(posting_source);

COMMENT ON COLUMN journal_entries.posting_source IS 
  'Posting source: ''system'' for automatic postings (retail sales, invoices, etc.), ''accountant'' for manual accountant postings. Determines authorization requirements.';

-- ============================================================================
-- STEP 2: Update authorization guard to check posting_source
-- ============================================================================
-- Update validate_accountant_posting to only require posted_by_accountant_id
-- when posting_source = 'accountant'
CREATE OR REPLACE FUNCTION validate_accountant_posting(
  p_posted_by_accountant_id UUID,
  p_business_id UUID,
  p_posting_source TEXT
)
RETURNS BOOLEAN AS $$
DECLARE
  is_accountant BOOLEAN;
BEGIN
  -- For accountant postings, posted_by_accountant_id is REQUIRED
  IF p_posting_source = 'accountant' THEN
    IF p_posted_by_accountant_id IS NULL THEN
      RAISE EXCEPTION 'posted_by_accountant_id is required for accountant postings. Only accountants can post ledger entries manually.';
    END IF;
    
    -- Verify user is accountant for this business
    is_accountant := is_user_accountant(p_posted_by_accountant_id, p_business_id);
    
    IF NOT is_accountant THEN
      RAISE EXCEPTION 'User % does not have accountant role for business %. Only accountants can post ledger entries manually.', p_posted_by_accountant_id, p_business_id;
    END IF;
  END IF;
  
  -- For system postings, posted_by_accountant_id is NOT required
  -- System postings are trusted (generated by application logic)
  
  RETURN TRUE;
END;
$$ LANGUAGE plpgsql;

-- Update trigger function to pass posting_source
CREATE OR REPLACE FUNCTION enforce_accountant_only_posting()
RETURNS TRIGGER AS $$
BEGIN
  -- Validate based on posting_source
  PERFORM validate_accountant_posting(
    NEW.posted_by_accountant_id, 
    NEW.business_id,
    NEW.posting_source
  );
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION validate_accountant_posting(UUID, UUID, TEXT) IS 
  'Validates accountant authorization based on posting_source. For accountant postings, requires posted_by_accountant_id and verifies accountant role. For system postings, no authorization required.';

COMMENT ON FUNCTION enforce_accountant_only_posting IS 
  'Trigger function that enforces accountant authorization based on posting_source. Only requires posted_by_accountant_id for accountant postings.';

-- ============================================================================
-- STEP 3: Update post_journal_entry() to accept posting_source
-- ============================================================================
-- Drop all existing overloads first
DROP FUNCTION IF EXISTS post_journal_entry(UUID, DATE, TEXT, TEXT, UUID, JSONB, BOOLEAN, TEXT, TEXT, UUID, TEXT, TEXT, TEXT, UUID) CASCADE;
DROP FUNCTION IF EXISTS post_journal_entry(UUID, DATE, TEXT, TEXT, UUID, JSONB, BOOLEAN, TEXT, TEXT, UUID, TEXT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS post_journal_entry(UUID, DATE, TEXT, TEXT, UUID, JSONB, BOOLEAN, TEXT, TEXT, UUID) CASCADE;
DROP FUNCTION IF EXISTS post_journal_entry(UUID, DATE, TEXT, TEXT, UUID, JSONB) CASCADE;

-- Create 15-parameter version with posting_source
CREATE OR REPLACE FUNCTION post_journal_entry(
  p_business_id UUID,
  p_date DATE,
  p_description TEXT,
  p_reference_type TEXT,
  p_reference_id UUID,
  p_lines JSONB,
  p_is_adjustment BOOLEAN DEFAULT FALSE,
  p_adjustment_reason TEXT DEFAULT NULL,
  p_adjustment_ref TEXT DEFAULT NULL,
  p_created_by UUID DEFAULT NULL,
  p_entry_type TEXT DEFAULT NULL,
  p_backfill_reason TEXT DEFAULT NULL,
  p_backfill_actor TEXT DEFAULT NULL,
  p_posted_by_accountant_id UUID DEFAULT NULL,
  p_posting_source TEXT DEFAULT 'accountant'
)
RETURNS UUID AS $$
DECLARE
  journal_id UUID;
  line JSONB;
  total_debit NUMERIC := 0;
  total_credit NUMERIC := 0;
  account_id UUID;
  system_accountant_id UUID;
BEGIN
  -- Validate posting_source
  IF p_posting_source NOT IN ('system', 'accountant') THEN
    RAISE EXCEPTION 'posting_source must be ''system'' or ''accountant''. Found: %', p_posting_source;
  END IF;

  -- PHASE 6: Validate adjustment metadata
  IF p_is_adjustment = TRUE THEN
    IF p_adjustment_reason IS NULL OR TRIM(p_adjustment_reason) = '' THEN
      RAISE EXCEPTION 'Adjustment entries require a non-empty adjustment_reason';
    END IF;
    IF p_reference_type != 'adjustment' THEN
      RAISE EXCEPTION 'Adjustment entries must have reference_type = ''adjustment''. Found: %', p_reference_type;
    END IF;
    IF p_reference_id IS NOT NULL THEN
      RAISE EXCEPTION 'Adjustment entries must have reference_id = NULL. Adjustments are standalone entries.';
    END IF;
  ELSE
    IF p_adjustment_reason IS NOT NULL OR p_adjustment_ref IS NOT NULL THEN
      RAISE EXCEPTION 'Non-adjustment entries cannot have adjustment_reason or adjustment_ref';
    END IF;
  END IF;

  -- PHASE 12: Backfill entries must have reason and actor
  IF p_entry_type = 'backfill' THEN
    IF p_backfill_reason IS NULL OR TRIM(p_backfill_reason) = '' THEN
      RAISE EXCEPTION 'Backfill entries require a non-empty backfill_reason';
    END IF;
    IF p_backfill_actor IS NULL OR TRIM(p_backfill_actor) = '' THEN
      RAISE EXCEPTION 'Backfill entries require a non-empty backfill_actor';
    END IF;
  END IF;

  -- Validate that debits equal credits BEFORE inserting
  FOR line IN SELECT * FROM jsonb_array_elements(p_lines)
  LOOP
    total_debit := total_debit + COALESCE((line->>'debit')::NUMERIC, 0);
    total_credit := total_credit + COALESCE((line->>'credit')::NUMERIC, 0);
  END LOOP;

  IF ABS(total_debit - total_credit) > 0.01 THEN
    RAISE EXCEPTION 'Journal entry must balance. Debit: %, Credit: %', total_debit, total_credit;
  END IF;

  -- Get system accountant (for system postings when posted_by_accountant_id not provided)
  IF p_posting_source = 'system' AND p_posted_by_accountant_id IS NULL THEN
    -- Default to business owner as system accountant for system postings
    SELECT owner_id INTO system_accountant_id
    FROM businesses
    WHERE id = p_business_id;
    
    IF system_accountant_id IS NULL THEN
      RAISE EXCEPTION 'Cannot post journal entry: Business owner not found for business %. System accountant required for automatic posting.', p_business_id;
    END IF;
  END IF;

  -- Create journal entry with posting_source
  INSERT INTO journal_entries (
    business_id,
    date,
    description,
    reference_type,
    reference_id,
    created_by,
    is_adjustment,
    adjustment_reason,
    adjustment_ref,
    entry_type,
    backfill_reason,
    backfill_actor,
    posted_by_accountant_id,
    posting_source
  )
  VALUES (
    p_business_id,
    p_date,
    p_description,
    p_reference_type,
    p_reference_id,
    COALESCE(p_created_by, system_accountant_id, p_posted_by_accountant_id),
    p_is_adjustment,
    p_adjustment_reason,
    p_adjustment_ref,
    p_entry_type,
    p_backfill_reason,
    p_backfill_actor,
    COALESCE(p_posted_by_accountant_id, system_accountant_id),
    p_posting_source
  )
  RETURNING id INTO journal_id;

  -- Insert ALL lines in a SINGLE batch INSERT statement
  INSERT INTO journal_entry_lines (
    journal_entry_id,
    account_id,
    debit,
    credit,
    description
  )
  SELECT
    journal_id,
    (line->>'account_id')::UUID,
    COALESCE((line->>'debit')::NUMERIC, 0),
    COALESCE((line->>'credit')::NUMERIC, 0),
    line->>'description'
  FROM jsonb_array_elements(p_lines) AS line;

  RETURN journal_id;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION post_journal_entry(UUID, DATE, TEXT, TEXT, UUID, JSONB, BOOLEAN, TEXT, TEXT, UUID, TEXT, TEXT, TEXT, UUID, TEXT) IS 
  'FIX: Posts journal entry with posting_source parameter. System postings do not require posted_by_accountant_id. Accountant postings require posted_by_accountant_id and accountant role verification. Uses batch INSERT for all lines.';

-- ============================================================================
-- STEP 4: Recreate 14-parameter wrapper (backward compatibility)
-- ============================================================================
CREATE OR REPLACE FUNCTION post_journal_entry(
  p_business_id UUID,
  p_date DATE,
  p_description TEXT,
  p_reference_type TEXT,
  p_reference_id UUID,
  p_lines JSONB,
  p_is_adjustment BOOLEAN DEFAULT FALSE,
  p_adjustment_reason TEXT DEFAULT NULL,
  p_adjustment_ref TEXT DEFAULT NULL,
  p_created_by UUID DEFAULT NULL,
  p_entry_type TEXT DEFAULT NULL,
  p_backfill_reason TEXT DEFAULT NULL,
  p_backfill_actor TEXT DEFAULT NULL,
  p_posted_by_accountant_id UUID DEFAULT NULL
)
RETURNS UUID AS $$
BEGIN
  -- Default to 'accountant' for backward compatibility (manual postings)
  RETURN post_journal_entry(
    p_business_id => p_business_id,
    p_date => p_date,
    p_description => p_description,
    p_reference_type => p_reference_type,
    p_reference_id => p_reference_id,
    p_lines => p_lines,
    p_is_adjustment => p_is_adjustment,
    p_adjustment_reason => p_adjustment_reason,
    p_adjustment_ref => p_adjustment_ref,
    p_created_by => p_created_by,
    p_entry_type => p_entry_type,
    p_backfill_reason => p_backfill_reason,
    p_backfill_actor => p_backfill_actor,
    p_posted_by_accountant_id => p_posted_by_accountant_id,
    p_posting_source => 'accountant'  -- Default to accountant for manual postings
  );
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION post_journal_entry(UUID, DATE, TEXT, TEXT, UUID, JSONB, BOOLEAN, TEXT, TEXT, UUID, TEXT, TEXT, TEXT, UUID) IS 
  'Backward compatibility wrapper for 14-parameter post_journal_entry. Defaults to posting_source = ''accountant'' for manual postings.';

-- ============================================================================
-- STEP 5: Recreate 10-parameter wrapper (backward compatibility)
-- ============================================================================
CREATE OR REPLACE FUNCTION post_journal_entry(
  p_business_id UUID,
  p_date DATE,
  p_description TEXT,
  p_reference_type TEXT,
  p_reference_id UUID,
  p_lines JSONB,
  p_is_adjustment BOOLEAN,
  p_adjustment_reason TEXT,
  p_adjustment_ref TEXT,
  p_created_by UUID
)
RETURNS UUID AS $$
BEGIN
  -- Default to 'accountant' for backward compatibility (manual postings)
  RETURN post_journal_entry(
    p_business_id => p_business_id,
    p_date => p_date,
    p_description => p_description,
    p_reference_type => p_reference_type,
    p_reference_id => p_reference_id,
    p_lines => p_lines,
    p_is_adjustment => p_is_adjustment,
    p_adjustment_reason => p_adjustment_reason,
    p_adjustment_ref => p_adjustment_ref,
    p_created_by => p_created_by,
    p_entry_type => NULL::TEXT,
    p_backfill_reason => NULL::TEXT,
    p_backfill_actor => NULL::TEXT,
    p_posted_by_accountant_id => NULL::UUID,
    p_posting_source => 'accountant'  -- Default to accountant for manual postings
  );
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION post_journal_entry(UUID, DATE, TEXT, TEXT, UUID, JSONB, BOOLEAN, TEXT, TEXT, UUID) IS 
  'Backward compatibility wrapper for 10-parameter post_journal_entry. Defaults to posting_source = ''accountant'' for manual postings.';

-- ============================================================================
-- STEP 6: Update post_sale_to_ledger() to use posting_source = 'system'
-- ============================================================================
-- Drop all existing overloads first to avoid ambiguity
-- Use a DO block to dynamically drop all overloads
DO $$
DECLARE
  func_record RECORD;
BEGIN
  FOR func_record IN 
    SELECT pg_get_function_identity_arguments(oid) as args
    FROM pg_proc
    WHERE proname = 'post_sale_to_ledger'
      AND pronamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public')
  LOOP
    EXECUTE format('DROP FUNCTION IF EXISTS post_sale_to_ledger(%s) CASCADE', func_record.args);
  END LOOP;
END $$;

-- Create the function with explicit posting_source = 'system'
CREATE OR REPLACE FUNCTION post_sale_to_ledger(
  p_sale_id UUID,
  p_entry_type TEXT DEFAULT NULL,
  p_backfill_reason TEXT DEFAULT NULL,
  p_backfill_actor TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
  sale_record RECORD;
  business_id_val UUID;
  cash_account_id UUID;
  revenue_account_id UUID;
  cogs_account_id UUID;
  inventory_account_id UUID;
  journal_id UUID;
  subtotal NUMERIC;
  tax_lines_jsonb JSONB;
  tax_line_item JSONB;
  parsed_tax_lines JSONB[] := ARRAY[]::JSONB[];
  journal_lines JSONB;
  tax_account_id UUID;
  tax_code TEXT;
  tax_amount NUMERIC;
  tax_ledger_side TEXT;
  tax_ledger_account_code TEXT;
  total_tax_amount NUMERIC := 0;
  cash_account_code TEXT;
  total_cogs NUMERIC := 0;
BEGIN
  -- Get sale details
  SELECT 
    s.business_id,
    s.amount,
    s.created_at,
    s.description,
    s.tax_lines
  INTO sale_record
  FROM sales s
  WHERE s.id = p_sale_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Sale not found: %', p_sale_id;
  END IF;

  business_id_val := sale_record.business_id;

  -- GUARD: Assert accounting period is open
  PERFORM assert_accounting_period_is_open(business_id_val, sale_record.created_at::DATE);

  -- Calculate total COGS from sale_items
  SELECT COALESCE(SUM(COALESCE(cogs, 0)), 0)
  INTO total_cogs
  FROM sale_items
  WHERE sale_id = p_sale_id;

  -- Parse tax_lines JSONB metadata
  tax_lines_jsonb := sale_record.tax_lines;
  IF tax_lines_jsonb IS NOT NULL THEN
    -- Handle both formats: object with tax_lines key, or direct array
    IF jsonb_typeof(tax_lines_jsonb) = 'object' AND tax_lines_jsonb ? 'tax_lines' THEN
      tax_lines_jsonb := tax_lines_jsonb->'tax_lines';
    END IF;
    -- Validate it's an array and parse individual tax line items
    IF jsonb_typeof(tax_lines_jsonb) = 'array' THEN
      FOR tax_line_item IN SELECT * FROM jsonb_array_elements(tax_lines_jsonb)
      LOOP
        -- Defensive validation: ensure tax line has required fields
        IF tax_line_item ? 'code' AND tax_line_item ? 'amount' THEN
          parsed_tax_lines := array_append(parsed_tax_lines, tax_line_item);
          -- Sum tax amounts to calculate subtotal
          total_tax_amount := total_tax_amount + COALESCE((tax_line_item->>'amount')::NUMERIC, 0);
        END IF;
      END LOOP;
    END IF;
  END IF;

  -- Calculate subtotal: total - sum of all taxes
  subtotal := COALESCE(sale_record.amount, 0) - total_tax_amount;

  -- RETAIL FIX: Ensure CASH control account mapping exists before use
  BEGIN
    PERFORM ensure_retail_control_account_mapping(business_id_val, 'CASH', '1000');
  EXCEPTION
    WHEN OTHERS THEN
      -- Re-raise with context about Retail sales requirement
      RAISE EXCEPTION 'Cannot post sale to ledger: % (Business: %, Sale: %)', 
        SQLERRM, business_id_val, p_sale_id;
  END;

  -- COA GUARD: Validate all accounts exist before posting
  cash_account_code := get_control_account_code(business_id_val, 'CASH');
  PERFORM assert_account_exists(business_id_val, cash_account_code);
  PERFORM assert_account_exists(business_id_val, '4000'); -- Revenue (not a control key)
  PERFORM assert_account_exists(business_id_val, '5000'); -- COGS Expense
  PERFORM assert_account_exists(business_id_val, '1200'); -- Inventory Asset
  
  -- Validate tax account codes from tax_lines
  FOR tax_line_item IN SELECT * FROM unnest(parsed_tax_lines)
  LOOP
    tax_ledger_account_code := tax_line_item->>'ledger_account_code';
    IF tax_ledger_account_code IS NOT NULL AND COALESCE((tax_line_item->>'amount')::NUMERIC, 0) > 0 THEN
      PERFORM assert_account_exists(business_id_val, tax_ledger_account_code);
    END IF;
  END LOOP;

  -- Get account IDs using control keys and codes
  cash_account_id := get_account_by_control_key(business_id_val, 'CASH');
  revenue_account_id := get_account_by_code(business_id_val, '4000'); -- Sales Revenue (not a control key)
  cogs_account_id := get_account_by_code(business_id_val, '5000'); -- Cost of Sales
  inventory_account_id := get_account_by_code(business_id_val, '1200'); -- Inventory Asset

  -- Validate all required accounts exist
  IF cash_account_id IS NULL THEN
    RAISE EXCEPTION 'Cash account not found for business: %', business_id_val;
  END IF;
  IF revenue_account_id IS NULL THEN
    RAISE EXCEPTION 'Revenue account (4000) not found for business: %', business_id_val;
  END IF;
  IF cogs_account_id IS NULL THEN
    RAISE EXCEPTION 'COGS account (5000) not found for business: %', business_id_val;
  END IF;
  IF inventory_account_id IS NULL THEN
    RAISE EXCEPTION 'Inventory account (1200) not found for business: %', business_id_val;
  END IF;

  -- Build journal entry lines: start with base lines (Cash, Revenue, COGS, Inventory)
  journal_lines := jsonb_build_array(
    jsonb_build_object(
      'account_id', cash_account_id,
      'debit', sale_record.amount,
      'description', 'Sale receipt'
    ),
    jsonb_build_object(
      'account_id', revenue_account_id,
      'credit', subtotal,
      'description', 'Sales revenue'
    ),
    jsonb_build_object(
      'account_id', cogs_account_id,
      'debit', total_cogs,
      'description', 'Cost of goods sold'
    ),
    jsonb_build_object(
      'account_id', inventory_account_id,
      'credit', total_cogs,
      'description', 'Inventory reduction'
    )
  );

  -- Add tax lines: iterate parsed_tax_lines and post each to its control account
  -- Sales tax lines are always output taxes (credit side)
  FOR tax_line_item IN SELECT * FROM unnest(parsed_tax_lines)
  LOOP
    tax_code := tax_line_item->>'code';
    tax_amount := COALESCE((tax_line_item->>'amount')::NUMERIC, 0);
    tax_ledger_account_code := tax_line_item->>'ledger_account_code';
    tax_ledger_side := tax_line_item->>'ledger_side';

    -- Only post tax lines with ledger_account_code (sales don't have absorbed taxes)
    IF tax_ledger_account_code IS NOT NULL AND tax_amount > 0 THEN
      tax_account_id := get_account_by_code(business_id_val, tax_ledger_account_code);
      
      -- Build tax journal line based on ledger_side (should be 'credit' for sales output taxes)
      IF tax_ledger_side = 'credit' THEN
        journal_lines := journal_lines || jsonb_build_array(
          jsonb_build_object(
            'account_id', tax_account_id,
            'credit', tax_amount,
            'description', COALESCE(tax_code, 'Tax') || ' tax'
          )
        );
      ELSIF tax_ledger_side = 'debit' THEN
        journal_lines := journal_lines || jsonb_build_array(
          jsonb_build_object(
            'account_id', tax_account_id,
            'debit', tax_amount,
            'description', COALESCE(tax_code, 'Tax') || ' tax'
          )
        );
      END IF;
    END IF;
  END LOOP;

  -- Post journal entry with posting_source = 'system' (RETAIL FIX)
  -- System postings do not require posted_by_accountant_id
  SELECT post_journal_entry(
    business_id_val,
    sale_record.created_at::DATE,
    'Sale' || COALESCE(': ' || sale_record.description, ''),
    'sale',
    p_sale_id,
    journal_lines,
    FALSE,  -- p_is_adjustment
    NULL,   -- p_adjustment_reason
    NULL,   -- p_adjustment_ref
    NULL,   -- p_created_by
    p_entry_type,
    p_backfill_reason,
    p_backfill_actor,
    NULL,   -- p_posted_by_accountant_id (not required for system postings)
    'system'  -- p_posting_source: RETAIL postings are system-generated
  ) INTO journal_id;

  RETURN journal_id;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION post_sale_to_ledger IS 
  'RETAIL FIX: Posts sale to ledger with posting_source = ''system''. System postings do not require posted_by_accountant_id. Optional p_entry_type, p_backfill_reason, p_backfill_actor for Phase 12 backfill.';

-- ============================================================================
-- STEP 7: Update apply_adjusting_journal() to use posting_source = 'accountant'
-- ============================================================================
-- This function calls post_journal_entry, which now defaults to 'accountant'
-- but we make it explicit for clarity
CREATE OR REPLACE FUNCTION apply_adjusting_journal(
  p_business_id UUID,
  p_period_start DATE,
  p_entry_date DATE,
  p_description TEXT,
  p_lines JSONB,
  p_created_by UUID,
  p_adjustment_reason TEXT,
  p_adjustment_ref TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
  v_period RECORD;
  v_account RECORD;
  v_journal_entry_id UUID;
  v_line JSONB;
  v_total_debit NUMERIC := 0;
  v_total_credit NUMERIC := 0;
  v_account_id UUID;
  v_debit NUMERIC;
  v_credit NUMERIC;
  v_line_count INTEGER := 0;
  v_affected_accounts JSONB := '[]'::jsonb;
  v_account_code TEXT;
  v_account_name TEXT;
  v_period_id UUID;
BEGIN
  -- ========================================================================
  -- VALIDATION 1: Period exists and status allows adjustments
  -- ========================================================================
  SELECT * INTO v_period
  FROM accounting_periods
  WHERE business_id = p_business_id
    AND period_start = p_period_start;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Accounting period not found for period_start: %', p_period_start;
  END IF;

  v_period_id := v_period.id;

  -- PHASE 6: Allow adjustments in 'open' OR 'soft_closed' periods
  -- Block adjustments in 'locked' periods
  IF v_period.status = 'locked' THEN
    RAISE EXCEPTION 'Adjusting journals cannot be posted into locked periods. Period status: %.', v_period.status;
  END IF;

  IF v_period.status NOT IN ('open', 'soft_closed') THEN
    RAISE EXCEPTION 'Adjusting journals can only be posted into periods with status ''open'' or ''soft_closed''. Period status: %.', v_period.status;
  END IF;

  -- ========================================================================
  -- VALIDATION 2: entry_date must fall within period [period_start, period_end]
  -- ========================================================================
  IF p_entry_date < v_period.period_start OR p_entry_date > v_period.period_end THEN
    RAISE EXCEPTION 'Entry date % must fall within period [%, %]', p_entry_date, v_period.period_start, v_period.period_end;
  END IF;

  -- ========================================================================
  -- VALIDATION 3: adjustment_reason is required
  -- ========================================================================
  IF p_adjustment_reason IS NULL OR TRIM(p_adjustment_reason) = '' THEN
    RAISE EXCEPTION 'Adjustment reason is required and cannot be empty';
  END IF;

  -- ========================================================================
  -- VALIDATION 4: At least 2 lines required
  -- ========================================================================
  v_line_count := jsonb_array_length(p_lines);
  IF v_line_count < 2 THEN
    RAISE EXCEPTION 'Adjusting journal must have at least 2 lines. Found: %', v_line_count;
  END IF;

  -- ========================================================================
  -- VALIDATION 5: Validate accounts and compute totals
  -- ========================================================================
  FOR v_line IN SELECT * FROM jsonb_array_elements(p_lines)
  LOOP
    -- Validate required fields
    IF NOT (v_line ? 'account_id') THEN
      RAISE EXCEPTION 'Each line must have an account_id';
    END IF;

    v_account_id := (v_line->>'account_id')::UUID;

    -- Validate account exists and belongs to business
    SELECT * INTO v_account
    FROM accounts
    WHERE id = v_account_id
      AND business_id = p_business_id
      AND deleted_at IS NULL;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Account not found or does not belong to business: %', v_account_id;
    END IF;

    v_account_code := v_account.code;
    v_account_name := v_account.name;

    -- Validate amounts
    v_debit := COALESCE((v_line->>'debit')::NUMERIC, 0);
    v_credit := COALESCE((v_line->>'credit')::NUMERIC, 0);

    -- Exactly one of debit or credit must be > 0
    IF v_debit <= 0 AND v_credit <= 0 THEN
      RAISE EXCEPTION 'Each line must have either debit > 0 or credit > 0';
    END IF;

    IF v_debit > 0 AND v_credit > 0 THEN
      RAISE EXCEPTION 'Each line must have either debit OR credit, not both';
    END IF;

    -- Accumulate totals
    v_total_debit := v_total_debit + v_debit;
    v_total_credit := v_total_credit + v_credit;

    -- Track affected accounts
    v_affected_accounts := v_affected_accounts || jsonb_build_object(
      'account_code', v_account_code,
      'account_name', v_account_name,
      'debit', v_debit,
      'credit', v_credit
    );
  END LOOP;

  -- ========================================================================
  -- VALIDATION 6: Debit/credit totals must balance exactly
  -- ========================================================================
  IF ABS(v_total_debit - v_total_credit) > 0.01 THEN
    RAISE EXCEPTION 'Adjusting journal entry must balance. Debit: %, Credit: %, Difference: %', v_total_debit, v_total_credit, ABS(v_total_debit - v_total_credit);
  END IF;

  -- ========================================================================
  -- CREATE JOURNAL ENTRY (using enhanced post_journal_entry function)
  -- ========================================================================
  -- PHASE 6: Use adjustment-only path with proper metadata
  -- EXPLICIT: Use posting_source = 'accountant' for manual accountant postings
  SELECT post_journal_entry(
    p_business_id,
    p_entry_date,
    p_description,
    'adjustment',  -- reference_type marks this as adjustment
    NULL,  -- reference_id is NULL (adjustments are standalone entries)
    p_lines,
    TRUE,  -- is_adjustment = TRUE
    p_adjustment_reason,  -- adjustment_reason (required)
    p_adjustment_ref,  -- adjustment_ref (optional)
    p_created_by,  -- created_by
    NULL,  -- p_entry_type
    NULL,  -- p_backfill_reason
    NULL,  -- p_backfill_actor
    p_created_by,  -- p_posted_by_accountant_id (required for accountant postings)
    'accountant'  -- p_posting_source: Manual adjustments are accountant postings
  ) INTO v_journal_entry_id;

  -- ========================================================================
  -- PHASE 6: MANDATORY AUDIT LOGGING
  -- ========================================================================
  INSERT INTO accounting_adjustment_audit (
    business_id,
    period_id,
    journal_entry_id,
    actor_user_id,
    adjustment_reason,
    adjustment_ref,
    affected_accounts,
    total_debit,
    total_credit
  )
  VALUES (
    p_business_id,
    v_period_id,
    v_journal_entry_id,
    p_created_by,
    p_adjustment_reason,
    p_adjustment_ref,
    v_affected_accounts,
    v_total_debit,
    v_total_credit
  );

  -- ========================================================================
  -- RETURN JOURNAL ENTRY ID
  -- ========================================================================
  RETURN v_journal_entry_id;

EXCEPTION
  WHEN OTHERS THEN
    -- Re-raise with context
    RAISE EXCEPTION 'Failed to apply adjusting journal: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION apply_adjusting_journal IS 
  'PHASE 6: Atomically validates and applies adjusting journal entry. Uses posting_source = ''accountant'' for manual accountant postings. Enforces period status = ''open'' or ''soft_closed'' (not locked), entry_date within period, account validation, balanced entry, minimum 2 lines, and required adjustment_reason. Creates new journal entry marked with is_adjustment=TRUE and reference_type=''adjustment''. Logs to accounting_adjustment_audit table. Adjustments are permanent and auditable.';

-- ============================================================================
-- STEP 8: Update post_adjustment_to_ledger() to set posting_source = 'accountant'
-- ============================================================================
CREATE OR REPLACE FUNCTION post_adjustment_to_ledger(
  p_business_id UUID,
  p_adjustment_date DATE,
  p_lines JSONB,
  p_reason TEXT,
  p_reference_journal_id UUID DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
  journal_id UUID;
  adjustment_id UUID;
  line JSONB;
  total_debit NUMERIC := 0;
  total_credit NUMERIC := 0;
  account_id UUID;
  account_code TEXT;
  period_start_date DATE;
BEGIN
  -- Validate reason is not empty
  IF p_reason IS NULL OR TRIM(p_reason) = '' THEN
    RAISE EXCEPTION 'Adjustment reason is mandatory and cannot be empty';
  END IF;

  -- Validate period using assert_accounting_period_is_open
  -- Adjustments CANNOT be posted into locked periods
  PERFORM assert_accounting_period_is_open(p_business_id, p_adjustment_date);

  -- Resolve period_start from adjustment_date
  period_start_date := DATE_TRUNC('month', p_adjustment_date)::DATE;

  -- COA GUARD: Validate all account codes from p_lines before journal inserts
  FOR line IN SELECT * FROM jsonb_array_elements(p_lines)
  LOOP
    account_code := line->>'account_code';
    IF account_code IS NULL THEN
      RAISE EXCEPTION 'Account code is required for each adjustment line';
    END IF;
    PERFORM assert_account_exists(p_business_id, account_code);
  END LOOP;

  -- Validate that adjustments MUST balance (total debit = total credit)
  FOR line IN SELECT * FROM jsonb_array_elements(p_lines)
  LOOP
    total_debit := total_debit + COALESCE((line->>'debit_amount')::NUMERIC, 0);
    total_credit := total_credit + COALESCE((line->>'credit_amount')::NUMERIC, 0);
  END LOOP;

  IF ABS(total_debit - total_credit) > 0.01 THEN
    RAISE EXCEPTION 'Adjustment journal entry must balance. Debit: %, Credit: %', total_debit, total_credit;
  END IF;

  -- Create journal entry with reference_type = 'adjustment' and posting_source = 'accountant'
  INSERT INTO journal_entries (
    business_id,
    date,
    description,
    reference_type,
    reference_id,
    created_by,
    posting_source
  )
  VALUES (
    p_business_id,
    p_adjustment_date,
    'Adjustment: ' || p_reason,
    'adjustment',
    NULL, -- reference_id is NULL for adjustments (metadata stored in accounting_adjustments)
    auth.uid(), -- Use current user from auth context
    'accountant'  -- Manual adjustments are accountant postings
  )
  RETURNING id INTO journal_id;

  -- Create journal entry lines
  FOR line IN SELECT * FROM jsonb_array_elements(p_lines)
  LOOP
    account_code := line->>'account_code';
    
    IF account_code IS NULL THEN
      RAISE EXCEPTION 'Account code is required for each adjustment line';
    END IF;

    -- Get account ID by code
    account_id := get_account_by_code(p_business_id, account_code);

    IF account_id IS NULL THEN
      RAISE EXCEPTION 'Account with code % not found for business: %', account_code, p_business_id;
    END IF;

    INSERT INTO journal_entry_lines (
      journal_entry_id,
      account_id,
      debit,
      credit,
      description
    )
    VALUES (
      journal_id,
      account_id,
      COALESCE((line->>'debit_amount')::NUMERIC, 0),
      COALESCE((line->>'credit_amount')::NUMERIC, 0),
      line->>'description'
    );
  END LOOP;

  -- Store metadata row in accounting_adjustments
  INSERT INTO accounting_adjustments (
    business_id,
    adjustment_date,
    period_start,
    reason,
    reference_journal_id,
    created_by
  )
  VALUES (
    p_business_id,
    p_adjustment_date,
    period_start_date,
    p_reason,
    p_reference_journal_id,
    auth.uid()
  )
  RETURNING id INTO adjustment_id;

  RETURN journal_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION post_adjustment_to_ledger IS 
  'Posts adjustment to ledger with posting_source = ''accountant''. Manual adjustments are accountant postings and require posted_by_accountant_id (set via created_by).';

-- ============================================================================
-- STEP 9: Update post_opening_balance_import_to_ledger() to set posting_source = 'accountant'
-- ============================================================================
-- Note: This function inserts directly into journal_entries, so we need to add posting_source
-- Read the function to find where it inserts
CREATE OR REPLACE FUNCTION post_opening_balance_import_to_ledger(
  p_import_id UUID,
  p_posted_by UUID
)
RETURNS UUID AS $$
DECLARE
  import_record RECORD;
  business_id_val UUID;
  period_id_val UUID;
  period_start_date DATE;
  period_end_date DATE;
  journal_entry_id_val UUID;
  existing_entry_id UUID;
  canonical_lines JSONB;
  input_hash_val TEXT;
  line JSONB;
  account_id_val UUID;
  account_code_val TEXT;
  debit_val NUMERIC;
  credit_val NUMERIC;
  memo_val TEXT;
BEGIN
  -- Get import record
  SELECT * INTO import_record
  FROM opening_balance_imports
  WHERE id = p_import_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Opening balance import not found: %', p_import_id;
  END IF;

  -- Validate import is in 'pending' status
  IF import_record.status != 'pending' THEN
    RAISE EXCEPTION 'Opening balance import must be in ''pending'' status. Current status: %', import_record.status;
  END IF;

  business_id_val := import_record.client_business_id;
  period_id_val := import_record.period_id;

  -- Get period dates
  SELECT period_start, period_end INTO period_start_date, period_end_date
  FROM accounting_periods
  WHERE id = period_id_val;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Accounting period not found: %', period_id_val;
  END IF;

  -- Convert lines to canonical format
  canonical_lines := COALESCE(import_record.canonical_lines, '[]'::jsonb);

  -- Compute input hash for idempotency
  IF import_record.input_hash IS NULL THEN
    input_hash_val := encode(
      digest(
        format(
          '%s|%s|%s|%s|%s|%s|%s|%s|%s',
          import_record.id,
          import_record.accounting_firm_id,
          import_record.client_business_id,
          import_record.period_id,
          import_record.source_type,
          canonical_lines::TEXT,
          ROUND(import_record.total_debit, 2)::TEXT,
          ROUND(import_record.total_credit, 2)::TEXT,
          COALESCE(import_record.approved_by::TEXT, '')
        ),
        'sha256'
      ),
      'hex'
    );
  ELSE
    input_hash_val := import_record.input_hash;
  END IF;

  -- ========================================================================
  -- STEP 9: IDEMPOTENCY CHECK - Check if ledger entry exists with same hash
  -- ========================================================================
  SELECT id INTO existing_entry_id
  FROM journal_entries
  WHERE source_type = 'opening_balance'
    AND input_hash = input_hash_val
  LIMIT 1;

  IF existing_entry_id IS NOT NULL THEN
    -- Link import to existing ledger entry
    UPDATE opening_balance_imports
    SET 
      journal_entry_id = existing_entry_id,
      posted_at = NOW(),
      posted_by = p_posted_by,
      status = 'posted',
      input_hash = input_hash_val
    WHERE id = p_import_id;

    RETURN existing_entry_id;
  END IF;

  -- ========================================================================
  -- STEP 10: CREATE LEDGER ENTRY + LINES (ATOMIC)
  -- ========================================================================
  -- Use period start date as the entry date for opening balances
  INSERT INTO journal_entries (
    business_id,
    date,
    description,
    reference_type,
    reference_id,
    created_by,
    source_type,
    source_import_id,
    input_hash,
    posting_source
  )
  VALUES (
    business_id_val,
    period_start_date,
    'Opening Balance Import',
    'opening_balance',
    NULL,
    p_posted_by,
    'opening_balance',
    p_import_id,
    input_hash_val,
    'accountant'  -- Opening balances are manual accountant postings
  )
  RETURNING id INTO journal_entry_id_val;

  -- Insert journal entry lines
  FOR line IN SELECT * FROM jsonb_array_elements(canonical_lines)
  LOOP
    account_code_val := line->>'account_code';
    debit_val := COALESCE((line->>'debit')::NUMERIC, 0);
    credit_val := COALESCE((line->>'credit')::NUMERIC, 0);
    memo_val := line->>'memo';

    -- Get account ID by code
    SELECT id INTO account_id_val
    FROM accounts
    WHERE business_id = business_id_val
      AND code = account_code_val
      AND deleted_at IS NULL;

    IF account_id_val IS NULL THEN
      RAISE EXCEPTION 'Account with code % not found for business: %', account_code_val, business_id_val;
    END IF;

    INSERT INTO journal_entry_lines (
      journal_entry_id,
      account_id,
      debit,
      credit,
      description
    )
    VALUES (
      journal_entry_id_val,
      account_id_val,
      debit_val,
      credit_val,
      COALESCE(memo_val, 'Opening balance')
    );
  END LOOP;

  -- Update import record
  UPDATE opening_balance_imports
  SET 
    journal_entry_id = journal_entry_id_val,
    posted_at = NOW(),
    posted_by = p_posted_by,
    status = 'posted',
    input_hash = input_hash_val
  WHERE id = p_import_id;

  RETURN journal_entry_id_val;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION post_opening_balance_import_to_ledger IS 
  'Posts opening balance import to ledger with posting_source = ''accountant''. Opening balances are manual accountant postings.';
